// 🍳 SaborBR - Banco de Receitas Externas (Simulação de API)
// Simula receitas de blogs, sites e chefs renomados

import { Recipe } from './types';

export const EXTERNAL_RECIPES: Recipe[] = [
  // ========== RECEITAS BRASILEIRAS ==========
  {
    id: 'ext-br-moqueca',
    title: 'Moqueca Capixaba',
    description: 'Tradicional moqueca do Espírito Santo com peixe fresco',
    image: 'https://images.unsplash.com/photo-1604152135912-04a022e23696?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Almoço',
    servings: 6,
    prepTime: 20,
    cookTime: 40,
    difficulty: 'Médio',
    ingredients: [
      { id: 'moqueca-1', name: 'Peixe (badejo ou robalo)', quantity: 1, unit: 'kg' },
      { id: 'moqueca-2', name: 'Tomate', quantity: 4, unit: 'unidades' },
      { id: 'moqueca-3', name: 'Cebola', quantity: 2, unit: 'unidades' },
      { id: 'moqueca-4', name: 'Pimentão', quantity: 2, unit: 'unidades' },
      { id: 'moqueca-5', name: 'Coentro', quantity: 1, unit: 'maço' },
      { id: 'moqueca-6', name: 'Azeite de dendê', quantity: 100, unit: 'ml' },
    ],
    instructions: [
      'Tempere o peixe com sal, limão e deixe marinar',
      'Em uma panela de barro, faça camadas de cebola, tomate e peixe',
      'Adicione o pimentão e o coentro',
      'Regue com azeite de dendê',
      'Cozinhe em fogo baixo por 40 minutos',
      'Sirva com arroz branco e pirão',
    ],
    nutrition: { calories: 380, protein: 42, carbs: 12, fat: 18 },
    tags: ['brasileira', 'capixaba', 'peixe', 'tradicional'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-renato',
    authorName: 'Chef Renato Souza',
    createdAt: new Date('2024-01-15').toISOString(),
    rating: 4.9,
    ratingsCount: 342,
    comments: [],
  },
  {
    id: 'ext-br-acaraje',
    title: 'Acarajé Baiano',
    description: 'Bolinho de feijão fradinho frito no azeite de dendê',
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Lanche',
    servings: 15,
    prepTime: 60,
    cookTime: 30,
    difficulty: 'Difícil',
    ingredients: [
      { id: 'acaraje-1', name: 'Feijão fradinho', quantity: 500, unit: 'g' },
      { id: 'acaraje-2', name: 'Cebola', quantity: 1, unit: 'unidade' },
      { id: 'acaraje-3', name: 'Sal', quantity: 1, unit: 'colher de chá' },
      { id: 'acaraje-4', name: 'Azeite de dendê', quantity: 500, unit: 'ml' },
      { id: 'acaraje-5', name: 'Camarão seco', quantity: 200, unit: 'g' },
      { id: 'acaraje-6', name: 'Vatapá', quantity: 300, unit: 'g' },
    ],
    instructions: [
      'Deixe o feijão de molho por 12 horas',
      'Retire a casca dos grãos',
      'Bata no liquidificador com cebola',
      'Tempere com sal',
      'Frite em azeite de dendê bem quente',
      'Recheie com vatapá, caruru e camarão',
    ],
    nutrition: { calories: 285, protein: 12, carbs: 28, fat: 14 },
    tags: ['brasileira', 'baiana', 'street food', 'tradicional'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-maria',
    authorName: 'Chef Maria Santos',
    createdAt: new Date('2024-01-20').toISOString(),
    rating: 4.8,
    ratingsCount: 289,
    comments: [],
  },
  {
    id: 'ext-br-bobo',
    title: 'Bobó de Camarão',
    description: 'Cremoso bobó de camarão com mandioca',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Almoço',
    servings: 4,
    prepTime: 30,
    cookTime: 40,
    difficulty: 'Médio',
    ingredients: [
      { id: 'bobo-1', name: 'Camarão médio', quantity: 500, unit: 'g' },
      { id: 'bobo-2', name: 'Mandioca', quantity: 800, unit: 'g' },
      { id: 'bobo-3', name: 'Leite de coco', quantity: 400, unit: 'ml' },
      { id: 'bobo-4', name: 'Azeite de dendê', quantity: 3, unit: 'colheres de sopa' },
      { id: 'bobo-5', name: 'Tomate', quantity: 2, unit: 'unidades' },
      { id: 'bobo-6', name: 'Coentro', quantity: 1, unit: 'maço' },
    ],
    instructions: [
      'Cozinhe a mandioca até ficar macia',
      'Bata no liquidificador com leite de coco',
      'Refogue o camarão com alho e tomate',
      'Adicione o purê de mandioca',
      'Acrescente o azeite de dendê',
      'Finalize com coentro picado',
    ],
    nutrition: { calories: 420, protein: 28, carbs: 35, fat: 20 },
    tags: ['brasileira', 'camarão', 'cremoso', 'especial'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-paulo',
    authorName: 'Chef Paulo Lima',
    createdAt: new Date('2024-02-01').toISOString(),
    rating: 4.9,
    ratingsCount: 412,
    comments: [],
  },

  // ========== DOCES ==========
  {
    id: 'ext-doce-pudim',
    title: 'Pudim de Leite Condensado',
    description: 'Clássico pudim brasileiro cremoso',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800&h=600&fit=crop',
    category: 'Doces',
    mealType: 'Sobremesa',
    servings: 8,
    prepTime: 15,
    cookTime: 60,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'pudim-1', name: 'Leite condensado', quantity: 1, unit: 'lata' },
      { id: 'pudim-2', name: 'Leite', quantity: 500, unit: 'ml' },
      { id: 'pudim-3', name: 'Ovos', quantity: 3, unit: 'unidades' },
      { id: 'pudim-4', name: 'Açúcar', quantity: 200, unit: 'g' },
    ],
    instructions: [
      'Faça a calda com açúcar caramelizado',
      'Bata todos os ingredientes no liquidificador',
      'Despeje na forma caramelizada',
      'Asse em banho-maria por 60 minutos',
      'Deixe esfriar e desenforme',
    ],
    nutrition: { calories: 280, protein: 8, carbs: 42, fat: 9 },
    tags: ['doce', 'sobremesa', 'clássico', 'festa'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-ana',
    authorName: 'Chef Ana Paula',
    createdAt: new Date('2024-02-05').toISOString(),
    rating: 4.7,
    ratingsCount: 523,
    comments: [],
  },
  {
    id: 'ext-doce-quindim',
    title: 'Quindim',
    description: 'Doce tradicional português-brasileiro de gema',
    image: 'https://images.unsplash.com/photo-1587241321921-91a834d82ffc?w=800&h=600&fit=crop',
    category: 'Doces',
    mealType: 'Sobremesa',
    servings: 12,
    prepTime: 20,
    cookTime: 45,
    difficulty: 'Médio',
    ingredients: [
      { id: 'quindim-1', name: 'Gemas', quantity: 12, unit: 'unidades' },
      { id: 'quindim-2', name: 'Açúcar', quantity: 300, unit: 'g' },
      { id: 'quindim-3', name: 'Coco ralado', quantity: 200, unit: 'g' },
      { id: 'quindim-4', name: 'Manteiga', quantity: 50, unit: 'g' },
    ],
    instructions: [
      'Bata as gemas com açúcar',
      'Adicione o coco ralado e a manteiga derretida',
      'Despeje em forminhas untadas',
      'Asse em banho-maria a 180°C por 45 minutos',
      'Deixe esfriar e desenforme',
    ],
    nutrition: { calories: 195, protein: 4, carbs: 28, fat: 8 },
    tags: ['doce', 'tradicional', 'coco', 'festa'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-carla',
    authorName: 'Chef Carla Mendes',
    createdAt: new Date('2024-02-10').toISOString(),
    rating: 4.8,
    ratingsCount: 267,
    comments: [],
  },
  {
    id: 'ext-doce-bolo-cenoura',
    title: 'Bolo de Cenoura com Cobertura de Chocolate',
    description: 'O bolo mais amado do Brasil',
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=600&fit=crop',
    category: 'Doces',
    mealType: 'Sobremesa',
    servings: 12,
    prepTime: 20,
    cookTime: 40,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'bolo-cenoura-1', name: 'Cenoura', quantity: 3, unit: 'unidades' },
      { id: 'bolo-cenoura-2', name: 'Ovos', quantity: 3, unit: 'unidades' },
      { id: 'bolo-cenoura-3', name: 'Óleo', quantity: 180, unit: 'ml' },
      { id: 'bolo-cenoura-4', name: 'Açúcar', quantity: 300, unit: 'g' },
      { id: 'bolo-cenoura-5', name: 'Farinha de trigo', quantity: 300, unit: 'g' },
      { id: 'bolo-cenoura-6', name: 'Chocolate em pó', quantity: 4, unit: 'colheres de sopa' },
    ],
    instructions: [
      'Bata no liquidificador cenoura, ovos e óleo',
      'Misture com açúcar e farinha',
      'Adicione fermento',
      'Asse a 180°C por 40 minutos',
      'Faça a cobertura com chocolate e leite condensado',
      'Cubra o bolo ainda quente',
    ],
    nutrition: { calories: 320, protein: 5, carbs: 48, fat: 12 },
    tags: ['doce', 'bolo', 'clássico', 'chocolate'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-roberto',
    authorName: 'Chef Roberto Silva',
    createdAt: new Date('2024-02-15').toISOString(),
    rating: 4.9,
    ratingsCount: 891,
    comments: [],
  },

  // ========== SALGADOS ==========
  {
    id: 'ext-salg-1',
    title: 'Coxinha de Frango',
    description: 'Salgado mais popular do Brasil',
    image: 'https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=800&h=600&fit=crop',
    category: 'Salgados',
    mealType: 'Lanche',
    servings: 20,
    prepTime: 45,
    cookTime: 30,
    difficulty: 'Médio',
    ingredients: [
      { id: 'coxinha-1', name: 'Peito de frango', quantity: 500, unit: 'g' },
      { id: 'coxinha-2', name: 'Batata', quantity: 3, unit: 'unidades' },
      { id: 'coxinha-3', name: 'Farinha de trigo', quantity: 500, unit: 'g' },
      { id: 'coxinha-4', name: 'Caldo de galinha', quantity: 500, unit: 'ml' },
      { id: 'coxinha-5', name: 'Farinha de rosca', quantity: 200, unit: 'g' },
    ],
    instructions: [
      'Cozinhe e desfie o frango',
      'Refogue com temperos',
      'Faça a massa com batata e farinha',
      'Modele as coxinhas',
      'Empane e frite',
    ],
    nutrition: { calories: 180, protein: 12, carbs: 22, fat: 6 },
    tags: ['salgado', 'festa', 'frango', 'frito'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-lucas',
    authorName: 'Chef Lucas Almeida',
    createdAt: new Date('2024-02-20').toISOString(),
    rating: 4.8,
    ratingsCount: 678,
    comments: [],
  },
  {
    id: 'ext-salg-2',
    title: 'Pastel de Feira',
    description: 'Crocante pastel brasileiro recheado',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&h=600&fit=crop',
    category: 'Salgados',
    mealType: 'Lanche',
    servings: 15,
    prepTime: 30,
    cookTime: 20,
    difficulty: 'Médio',
    ingredients: [
      { id: 'pastel-1', name: 'Farinha de trigo', quantity: 500, unit: 'g' },
      { id: 'pastel-2', name: 'Cachaça', quantity: 50, unit: 'ml' },
      { id: 'pastel-3', name: 'Sal', quantity: 1, unit: 'colher de chá' },
      { id: 'pastel-4', name: 'Carne moída', quantity: 300, unit: 'g' },
      { id: 'pastel-5', name: 'Queijo mussarela', quantity: 200, unit: 'g' },
    ],
    instructions: [
      'Faça a massa com farinha, cachaça e sal',
      'Deixe descansar por 30 minutos',
      'Abra a massa bem fina',
      'Recheie com carne ou queijo',
      'Frite em óleo quente',
    ],
    nutrition: { calories: 220, protein: 10, carbs: 28, fat: 8 },
    tags: ['salgado', 'feira', 'crocante', 'tradicional'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-fernanda',
    authorName: 'Chef Fernanda Costa',
    createdAt: new Date('2024-02-25').toISOString(),
    rating: 4.7,
    ratingsCount: 445,
    comments: [],
  },
  {
    id: 'ext-salg-3',
    title: 'Empadão de Frango',
    description: 'Torta salgada recheada com frango',
    image: 'https://images.unsplash.com/photo-1619096252214-ef06c45683e3?w=800&h=600&fit=crop',
    category: 'Salgados',
    mealType: 'Almoço',
    servings: 8,
    prepTime: 40,
    cookTime: 50,
    difficulty: 'Médio',
    ingredients: [
      { id: 'empadao-1', name: 'Farinha de trigo', quantity: 400, unit: 'g' },
      { id: 'empadao-2', name: 'Manteiga', quantity: 200, unit: 'g' },
      { id: 'empadao-3', name: 'Frango desfiado', quantity: 500, unit: 'g' },
      { id: 'empadao-4', name: 'Milho', quantity: 1, unit: 'lata' },
      { id: 'empadao-5', name: 'Azeitona', quantity: 100, unit: 'g' },
    ],
    instructions: [
      'Faça a massa com farinha e manteiga',
      'Forre uma forma com metade da massa',
      'Adicione o recheio de frango',
      'Cubra com o restante da massa',
      'Asse a 180°C por 50 minutos',
    ],
    nutrition: { calories: 380, protein: 18, carbs: 35, fat: 18 },
    tags: ['salgado', 'torta', 'frango', 'família'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-marcos',
    authorName: 'Chef Marcos Oliveira',
    createdAt: new Date('2024-03-01').toISOString(),
    rating: 4.8,
    ratingsCount: 356,
    comments: [],
  },

  // ========== MAIS RECEITAS BRASILEIRAS ==========
  {
    id: 'ext-br-4',
    title: 'Baião de Dois',
    description: 'Arroz com feijão verde nordestino',
    image: 'https://images.unsplash.com/photo-1516684732162-798a0062be99?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Almoço',
    servings: 6,
    prepTime: 20,
    cookTime: 40,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'baiao-1', name: 'Arroz', quantity: 300, unit: 'g' },
      { id: 'baiao-2', name: 'Feijão verde', quantity: 200, unit: 'g' },
      { id: 'baiao-3', name: 'Queijo coalho', quantity: 200, unit: 'g' },
      { id: 'baiao-4', name: 'Bacon', quantity: 150, unit: 'g' },
      { id: 'baiao-5', name: 'Manteiga de garrafa', quantity: 3, unit: 'colheres de sopa' },
    ],
    instructions: [
      'Cozinhe o feijão verde',
      'Refogue o bacon e reserve',
      'Refogue o arroz na manteiga de garrafa',
      'Adicione o feijão cozido',
      'Misture o queijo coalho em cubos',
      'Finalize com o bacon',
    ],
    nutrition: { calories: 420, protein: 16, carbs: 52, fat: 16 },
    tags: ['brasileira', 'nordeste', 'arroz', 'tradicional'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-joao',
    authorName: 'Chef João Batista',
    createdAt: new Date('2024-03-05').toISOString(),
    rating: 4.7,
    ratingsCount: 298,
    comments: [],
  },
  {
    id: 'ext-br-5',
    title: 'Vatapá',
    description: 'Cremoso prato baiano com camarão',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Almoço',
    servings: 6,
    prepTime: 30,
    cookTime: 45,
    difficulty: 'Difícil',
    ingredients: [
      { id: 'vatapa-1', name: 'Camarão seco', quantity: 200, unit: 'g' },
      { id: 'vatapa-2', name: 'Pão francês', quantity: 4, unit: 'unidades' },
      { id: 'vatapa-3', name: 'Leite de coco', quantity: 400, unit: 'ml' },
      { id: 'vatapa-4', name: 'Amendoim', quantity: 150, unit: 'g' },
      { id: 'vatapa-5', name: 'Azeite de dendê', quantity: 100, unit: 'ml' },
      { id: 'vatapa-6', name: 'Gengibre', quantity: 1, unit: 'pedaço' },
    ],
    instructions: [
      'Hidrate o camarão seco',
      'Deixe o pão de molho no leite de coco',
      'Bata tudo no liquidificador',
      'Cozinhe mexendo sempre',
      'Adicione azeite de dendê',
      'Sirva com arroz branco',
    ],
    nutrition: { calories: 480, protein: 22, carbs: 38, fat: 28 },
    tags: ['brasileira', 'baiana', 'cremoso', 'camarão'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-isabel',
    authorName: 'Chef Isabel Reis',
    createdAt: new Date('2024-03-10').toISOString(),
    rating: 4.9,
    ratingsCount: 387,
    comments: [],
  },
  {
    id: 'ext-br-6',
    title: 'Picanha na Brasa',
    description: 'Churrasco brasileiro tradicional',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Almoço',
    servings: 8,
    prepTime: 15,
    cookTime: 30,
    difficulty: 'Médio',
    ingredients: [
      { id: 'picanha-1', name: 'Picanha', quantity: 1.5, unit: 'kg' },
      { id: 'picanha-2', name: 'Sal grosso', quantity: 100, unit: 'g' },
      { id: 'picanha-3', name: 'Alho', quantity: 6, unit: 'dentes' },
    ],
    instructions: [
      'Tempere a picanha com sal grosso',
      'Deixe descansar por 30 minutos',
      'Asse na churrasqueira em fogo alto',
      'Vire a cada 5 minutos',
      'Retire quando atingir o ponto desejado',
      'Sirva com farofa e vinagrete',
    ],
    nutrition: { calories: 520, protein: 45, carbs: 0, fat: 38 },
    tags: ['brasileira', 'churrasco', 'carne', 'festa'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-ricardo',
    authorName: 'Chef Ricardo Barbosa',
    createdAt: new Date('2024-03-15').toISOString(),
    rating: 4.9,
    ratingsCount: 756,
    comments: [],
  },
  {
    id: 'ext-br-7',
    title: 'Tapioca Recheada',
    description: 'Crepe brasileiro de goma de tapioca',
    image: 'https://images.unsplash.com/photo-1619740455993-9e4e0f8b9c8e?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Café da Manhã',
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'tapioca-1', name: 'Goma de tapioca', quantity: 200, unit: 'g' },
      { id: 'tapioca-2', name: 'Queijo minas', quantity: 150, unit: 'g' },
      { id: 'tapioca-3', name: 'Coco ralado', quantity: 100, unit: 'g' },
      { id: 'tapioca-4', name: 'Leite condensado', quantity: 4, unit: 'colheres de sopa' },
    ],
    instructions: [
      'Aqueça uma frigideira antiaderente',
      'Espalhe a goma formando um círculo',
      'Adicione o recheio de sua preferência',
      'Dobre ao meio',
      'Sirva imediatamente',
    ],
    nutrition: { calories: 220, protein: 8, carbs: 35, fat: 6 },
    tags: ['brasileira', 'café da manhã', 'sem glúten', 'rápido'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-juliana',
    authorName: 'Chef Juliana Martins',
    createdAt: new Date('2024-03-20').toISOString(),
    rating: 4.6,
    ratingsCount: 423,
    comments: [],
  },
  {
    id: 'ext-br-8',
    title: 'Escondidinho de Carne Seca',
    description: 'Purê de mandioca com carne seca desfiada',
    image: 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=800&h=600&fit=crop',
    category: 'Brasileira',
    mealType: 'Almoço',
    servings: 6,
    prepTime: 40,
    cookTime: 50,
    difficulty: 'Médio',
    ingredients: [
      { id: 'escondidinho-1', name: 'Carne seca', quantity: 500, unit: 'g' },
      { id: 'escondidinho-2', name: 'Mandioca', quantity: 1, unit: 'kg' },
      { id: 'escondidinho-3', name: 'Manteiga', quantity: 100, unit: 'g' },
      { id: 'escondidinho-4', name: 'Queijo parmesão', quantity: 150, unit: 'g' },
      { id: 'escondidinho-5', name: 'Cebola', quantity: 2, unit: 'unidades' },
    ],
    instructions: [
      'Dessalgue e cozinhe a carne seca',
      'Desfie a carne e refogue',
      'Cozinhe a mandioca e faça um purê',
      'Monte em camadas em um refratário',
      'Cubra com queijo ralado',
      'Gratine no forno',
    ],
    nutrition: { calories: 450, protein: 32, carbs: 42, fat: 18 },
    tags: ['brasileira', 'gratinado', 'carne seca', 'conforto'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-pedro',
    authorName: 'Chef Pedro Henrique',
    createdAt: new Date('2024-03-25').toISOString(),
    rating: 4.8,
    ratingsCount: 512,
    comments: [],
  },

  // ========== MAIS DOCES ==========
  {
    id: 'ext-doce-4',
    title: 'Beijinho de Coco',
    description: 'Docinho branco de coco ralado',
    image: 'https://images.unsplash.com/photo-1587241321921-91a834d82ffc?w=800&h=600&fit=crop',
    category: 'Doces',
    mealType: 'Sobremesa',
    servings: 25,
    prepTime: 10,
    cookTime: 15,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'beijinho-1', name: 'Leite condensado', quantity: 1, unit: 'lata' },
      { id: 'beijinho-2', name: 'Coco ralado', quantity: 100, unit: 'g' },
      { id: 'beijinho-3', name: 'Manteiga', quantity: 1, unit: 'colher de sopa' },
      { id: 'beijinho-4', name: 'Cravo', quantity: 25, unit: 'unidades' },
    ],
    instructions: [
      'Misture leite condensado, coco e manteiga',
      'Cozinhe mexendo até desgrudar',
      'Deixe esfriar',
      'Faça bolinhas',
      'Passe no coco ralado',
      'Decore com cravo',
    ],
    nutrition: { calories: 75, protein: 1, carbs: 12, fat: 2.5 },
    tags: ['doce', 'festa', 'coco', 'fácil'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-beatriz',
    authorName: 'Chef Beatriz Souza',
    createdAt: new Date('2024-04-01').toISOString(),
    rating: 4.7,
    ratingsCount: 634,
    comments: [],
  },
  {
    id: 'ext-doce-5',
    title: 'Pavê de Chocolate',
    description: 'Sobremesa gelada em camadas',
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=800&h=600&fit=crop',
    category: 'Doces',
    mealType: 'Sobremesa',
    servings: 10,
    prepTime: 30,
    cookTime: 0,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'pave-1', name: 'Biscoito maisena', quantity: 400, unit: 'g' },
      { id: 'pave-2', name: 'Leite', quantity: 1, unit: 'litro' },
      { id: 'pave-3', name: 'Chocolate em pó', quantity: 4, unit: 'colheres de sopa' },
      { id: 'pave-4', name: 'Creme de leite', quantity: 2, unit: 'latas' },
      { id: 'pave-5', name: 'Açúcar', quantity: 200, unit: 'g' },
    ],
    instructions: [
      'Faça um creme com leite, chocolate e açúcar',
      'Molhe os biscoitos no leite',
      'Monte camadas alternadas',
      'Cubra com creme de leite batido',
      'Leve à geladeira por 4 horas',
      'Decore com chocolate ralado',
    ],
    nutrition: { calories: 350, protein: 6, carbs: 48, fat: 15 },
    tags: ['doce', 'gelado', 'chocolate', 'festa'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-camila',
    authorName: 'Chef Camila Rocha',
    createdAt: new Date('2024-04-05').toISOString(),
    rating: 4.8,
    ratingsCount: 789,
    comments: [],
  },
  {
    id: 'ext-doce-6',
    title: 'Mousse de Maracujá',
    description: 'Mousse cremoso e refrescante',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&h=600&fit=crop',
    category: 'Doces',
    mealType: 'Sobremesa',
    servings: 6,
    prepTime: 15,
    cookTime: 0,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'mousse-1', name: 'Suco de maracujá', quantity: 200, unit: 'ml' },
      { id: 'mousse-2', name: 'Leite condensado', quantity: 1, unit: 'lata' },
      { id: 'mousse-3', name: 'Creme de leite', quantity: 1, unit: 'lata' },
      { id: 'mousse-4', name: 'Gelatina sem sabor', quantity: 1, unit: 'envelope' },
    ],
    instructions: [
      'Hidrate a gelatina',
      'Bata todos os ingredientes no liquidificador',
      'Adicione a gelatina dissolvida',
      'Despeje em taças',
      'Leve à geladeira por 3 horas',
    ],
    nutrition: { calories: 280, protein: 5, carbs: 38, fat: 12 },
    tags: ['doce', 'mousse', 'maracujá', 'gelado'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-daniela',
    authorName: 'Chef Daniela Lima',
    createdAt: new Date('2024-04-10').toISOString(),
    rating: 4.9,
    ratingsCount: 567,
    comments: [],
  },

  // ========== RECEITAS COM INGREDIENTES ESPECÍFICOS ==========
  {
    id: 'ext-tomate-1',
    title: 'Molho de Tomate Caseiro',
    description: 'Molho de tomate fresco e aromático',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop',
    category: 'Outras',
    mealType: 'Almoço',
    servings: 6,
    prepTime: 15,
    cookTime: 40,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'molho-tomate-1', name: 'Tomate', quantity: 1, unit: 'kg' },
      { id: 'molho-tomate-2', name: 'Cebola', quantity: 1, unit: 'unidade' },
      { id: 'molho-tomate-3', name: 'Alho', quantity: 4, unit: 'dentes' },
      { id: 'molho-tomate-4', name: 'Manjericão', quantity: 1, unit: 'maço' },
      { id: 'molho-tomate-5', name: 'Azeite', quantity: 4, unit: 'colheres de sopa' },
    ],
    instructions: [
      'Escalde os tomates e retire a pele',
      'Refogue alho e cebola no azeite',
      'Adicione os tomates picados',
      'Cozinhe por 30 minutos',
      'Adicione manjericão fresco',
      'Tempere com sal e pimenta',
    ],
    nutrition: { calories: 85, protein: 2, carbs: 12, fat: 4 },
    tags: ['molho', 'tomate', 'italiano', 'básico'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-giuseppe',
    authorName: 'Chef Giuseppe Rossi',
    createdAt: new Date('2024-04-15').toISOString(),
    rating: 4.7,
    ratingsCount: 345,
    comments: [],
  },
  {
    id: 'ext-tomate-2',
    title: 'Bruschetta de Tomate',
    description: 'Entrada italiana clássica',
    image: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=800&h=600&fit=crop',
    category: 'Italiana',
    mealType: 'Lanche',
    servings: 4,
    prepTime: 15,
    cookTime: 5,
    difficulty: 'Fácil',
    ingredients: [
      { id: 'bruschetta-1', name: 'Tomate', quantity: 4, unit: 'unidades' },
      { id: 'bruschetta-2', name: 'Pão italiano', quantity: 1, unit: 'unidade' },
      { id: 'bruschetta-3', name: 'Manjericão', quantity: 1, unit: 'maço' },
      { id: 'bruschetta-4', name: 'Alho', quantity: 2, unit: 'dentes' },
      { id: 'bruschetta-5', name: 'Azeite extra virgem', quantity: 4, unit: 'colheres de sopa' },
    ],
    instructions: [
      'Corte os tomates em cubos pequenos',
      'Misture com manjericão picado',
      'Tempere com sal, azeite e alho',
      'Toste fatias de pão',
      'Cubra com a mistura de tomate',
      'Sirva imediatamente',
    ],
    nutrition: { calories: 180, protein: 5, carbs: 28, fat: 6 },
    tags: ['italiana', 'entrada', 'tomate', 'rápido'],
    isFavorite: false,
    isPublic: true,
    authorId: 'chef-marco',
    authorName: 'Chef Marco Antonio',
    createdAt: new Date('2024-04-20').toISOString(),
    rating: 4.6,
    ratingsCount: 278,
    comments: [],
  },
];

// Função para buscar receitas por termo
export const searchRecipes = (query: string): Recipe[] => {
  const lowerQuery = query.toLowerCase().trim();
  
  if (!lowerQuery) return [];
  
  return EXTERNAL_RECIPES.filter(recipe => {
    // Busca no título
    if (recipe.title.toLowerCase().includes(lowerQuery)) return true;
    
    // Busca na descrição
    if (recipe.description.toLowerCase().includes(lowerQuery)) return true;
    
    // Busca nas tags
    if (recipe.tags.some(tag => tag.toLowerCase().includes(lowerQuery))) return true;
    
    // Busca nos ingredientes
    if (recipe.ingredients.some(ing => ing.name.toLowerCase().includes(lowerQuery))) return true;
    
    // Busca na categoria
    if (recipe.category.toLowerCase().includes(lowerQuery)) return true;
    
    return false;
  });
};

// Função para obter sugestões de busca
export const getSearchSuggestions = (query: string): string[] => {
  const lowerQuery = query.toLowerCase().trim();
  
  if (!lowerQuery || lowerQuery.length < 2) return [];
  
  const suggestions = new Set<string>();
  
  EXTERNAL_RECIPES.forEach(recipe => {
    // Adiciona títulos que correspondem
    if (recipe.title.toLowerCase().includes(lowerQuery)) {
      suggestions.add(recipe.title);
    }
    
    // Adiciona ingredientes que correspondem
    recipe.ingredients.forEach(ing => {
      if (ing.name.toLowerCase().includes(lowerQuery)) {
        suggestions.add(ing.name);
      }
    });
    
    // Adiciona tags que correspondem
    recipe.tags.forEach(tag => {
      if (tag.toLowerCase().includes(lowerQuery)) {
        suggestions.add(tag);
      }
    });
  });
  
  return Array.from(suggestions).slice(0, 8);
};

// Função para filtrar por categoria
export const getRecipesByCategory = (category: string): Recipe[] => {
  return EXTERNAL_RECIPES.filter(recipe => recipe.category === category);
};

// Função para obter receitas populares
export const getPopularRecipes = (limit: number = 6): Recipe[] => {
  return [...EXTERNAL_RECIPES]
    .sort((a, b) => b.ratingsCount - a.ratingsCount)
    .slice(0, limit);
};

// Função para obter receitas da comunidade (públicas)
export const getCommunityRecipes = (): Recipe[] => {
  return EXTERNAL_RECIPES.filter(recipe => recipe.isPublic);
};
